# This is a basic workflow to help you get started with Actions

name: sync schedule

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
    schedule:
     - cron: '15 18 * * *'
    # * is a special character in YAML so you have to quote this string
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: add config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # Runs a set of commands using the runners shell
      - name: add gitee remote
        run: git remote add gitee https://gitee.com/GuangzhouXingyi/imx6ull-document
      
      - name: pull gitee
        run: git pull gitee master 
      
      - name: push
        run: git push -f origin master
